### ISSUE TITLE
Where to put the things with the stuff?

### ISSUE THREAD

**Issue by GNYniamh** [GNYniamh/Gobot#6]
Ok so we have to choose a database to store in!  I'd recommend Redis!
So, what's up with Redis?
Redis is an open-source, in-memory key-value data store. A key-value data store is a type of NoSQL database in which keys serve as unique identifiers for their associated values. Any given Redis instance includes a number of databases, each of which can hold many different keys of a variety of data types.

https://www.digitalocean.com/community/cheatsheets/how-to-manage-redis-databases-and-keys

**Comment by morg0n** [comment]
I can take this and determine a DB

**Comment by GNYniamh** [comment]
resolved by #8 merge
